# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontend',
            name='description',
            field=models.TextField(default='description default text'),
        ),
    ]
