# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_frontend_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontend',
            name='job',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
